### PR TITLE
add Http meower to navbar

### PR DESCRIPTION
**Pull request by showierdata9978**

### CODE REVIEW

**Comment by tnix100** [comment]
Shouldn't http meower be more of an Easter egg?

I don't really see how it fits on the navbar of the main site

**Comment by showierdata9978** [comment]
> Shouldn't http meower be more of an Easter egg?
> 
> I don't really see how it fits on the navbar of the main site

idk, maybe

**Comment by showierdata9978** [comment]
whats is analytics btw?

**Comment by tnix100** [comment]
Wdym?

**Comment by showierdata9978** [comment]
> Wdym?

cf analytics

**Comment by showierdata9978** [comment]
oh, i see my mistake

**Comment by showierdata9978** [comment]
whats its analytics btw?

**Comment by tnix100** [comment]
Cloudflare analytics as in web analytics, viewing hostnames, referring sites, views, what os people are on, etc.

**Comment by showierdata9978** [comment]
> Cloudflare analytics as in web analytics, viewing hostnames, referring sites, views, what os people are on, etc.

i misspelled lol

**Pull request closed without merging**
