### PR TITLE
New Meower website

### PR DESCRIPTION
**Pull request by zedthehedgehog**

### CODE REVIEW

**Comment by JoshAtticus** [comment]
You should make the logo the orange one, so it works with dark mode.

**Comment by JoshAtticus** [comment]
This PR and branch sadly haven't been touched in a while, so I've decided to create a branch with a new design idea. I won't close this in case someone wants to continue making this.

**Comment by tnix100** [comment]
Closed as gone stale.

**Comment by JoshAtticus** [comment]
Hey tnix I feel like we should keep the branch in case of any potential updates

**Comment by tnix100** [comment]
> Hey tnix I feel like we should keep the branch in case of any potential updates

zed said I could delete it.

**Pull request closed without merging**
