### PR TITLE
Merge this conmitments.

### PR DESCRIPTION
**Pull request by alphacodes26**
Also can you invite me back?

### CODE REVIEW

**Comment by wgyt** [comment]
hey @alphacodes26 why are you trying to merge this into Bloctans-patch-1, shouldn't you try to merge this into master? Also, for whoever enabled Github Pages and set it to the newwed-1 branch, stop, <branch>.meower-website.pages.dev let's you preview a branch. Also, the site design included seems to be broken 
image

**Comment by alphacodes26** [comment]
oh okay.
but invite me back into the github organization if u can, or anyone

**Comment by wgyt** [comment]
yeah, i cant invite you myself, you'd need to talk to @MikeDev101

**Comment by MikeDev101** [comment]
@alphacodes26 reinvite sent.

**Comment by MikeDev101** [comment]
Converted to draft, since this needs some more work.

**Comment by MikeDev101** [comment]
Abandoned.

**Pull request closed without merging**
