### PR TITLE
i suck at coding

### PR DESCRIPTION
**Pull request by tehbarney86**

### CODE REVIEW

**Comment by WlodekM** [comment]
lgtm

**Comment by WlodekM** [comment]
think you should also add a linux badge since it also works there

**Review by NotFenixio — APPROVED** [review]
please test stuff next time 🙏

**Comment by WlodekM** [comment]
wait how do i approve im new to gh, my account is only 1 week old /hj

**Review by WlodekM — APPROVED** [review]
lgtm

**Pull request closed without merging**
